
services:
  step_api:
    build: ./api
    container_name: step_api
    ports:
      - "8000:8000"
    networks:
      - container_net

  devcontainer:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    container_name: devcontainer
    volumes:
      - .:/clear-shape  # mount repository into dev container (nneeded to synch with local folder)
      
      # Daniel
      - D:\3 Resources\Nextcloud FH Kiel\Ressourcen-KI-Gruppe\Datensätze\fabwave\1_raw:/clear-shape/data/1_raw/
      - D:\3 Resources\Nextcloud FH Kiel\Ressourcen-KI-Gruppe\Datensätze\fabwave\3_primary:/clear-shape/data/3_primary/
      - D:\3 Resources\Nextcloud FH Kiel\Ressourcen-KI-Gruppe\Datensätze\fabwave\4_feature:/clear-shape/data/4_feature/

      # Michel
      # - /home/michelkruse/Nextcloud/Ressourcen-KI-Gruppe/Datensätze/fabwave/1_raw:/clear-shape/data/1_raw/
      # - /home/michelkruse/Nextcloud/Ressourcen-KI-Gruppe/Datensätze/fabwave/3_primary:/clear-shape/data/3_primary/
      # - /home/michelkruse/Nextcloud/Ressourcen-KI-Gruppe/Datensätze/fabwave/4_feature:/clear-shape/data/4_feature/

    networks:
      - container_net
    depends_on:
      - step_api
    tty: true

networks:
  container_net:
    driver: bridge
