---
classes_total: 42
reg_feature_total: 6

encoder:
  input_size: 32
  encoding_size_min: 50
  encoding_size_max: 300
  dropout_rate: 0.5

header:
  layers_total_min: 5
  layers_total_max: 20
  units_per_layer_min: 32
  units_per_layer_max: 256
