---
n_trials: 1 # number of trials per stage
n_jobs: 1  # number of parallel jobs
stages: [test]  # list of stages to run if possibel. (valid: train, validation, test)
n_epochs: 20
input_size: 32
output_shape: 6  # number of classes or regression targets to predict
loss_function: cross_entropy  # valid options: cross_entropy, mean_squared_error
test_metric: cross_entropy  # TODO use f1_score for classification
file_best_parameter: tree-lstm-classifier-best-parameter.yaml
# ------------------------------------

# Hyperparameters to optimize on training data
# Focus on model architecture

train:

  # fixed hyperparameters for training stage
  batch_size: 256  # preferably high for faster training
  learning_rate: 0.04
  optimizer: adam
  
  # hyperparameters to tune during training stage

  encoder:
    encoding_size_min: 250
    encoding_size_max: 250
    encoding_size_step: 50

  predictor:
    layers_total_min: 3
    layers_total_max: 3
    units_per_layer_min: 256
    units_per_layer_max: 256
# ------------------------------------

# Hyperparameters to optimize on validation data
# Focus on generalization and regularization
validation:

  # fixed hyperparameters for validation stage
  batch_size: 128  # preferably high for faster training
  optimizer: adam

  # hyperparameters to tune during validation stage
  learning_rate_min: 0.0001
  learning_rate_max: 0.1

  encoder:
    dropout_rate_min: 0.0
    dropout_rate_max: 0.9
# ------------------------------------

# Hyperparameters to optimize on test data
# Focus on final performance and robustness
test:

  # fixed hyperparameters for test stage
  optimizer: adam

  # hyperparameters to tune during test stage
  batch_size_min: 16
  batch_size_max: 16
  batch_size_step: 16

