---
n_trials: 2  # number of trials per stage
n_jobs: 2  # number of parallel jobs
stages: [train,]  # list of stages to run if possibel. (valid: train, val, test)
n_epochs: 200
input_size: 32
classes_total: 42
features_total: 4
loss_function: mean_squared_error
test_metric: mean_squared_error

# Hyperparameters to optimize on training data
# Focus on model size and learning ability
train:
  
  learning_rate_min: 0.0001
  learning_rate_max: 0.1
  batch_size_min: 32
  batch_size_max: 256
  
  encoder:
    encoding_size_min: 50
    encoding_size_max: 300
    dropout_rate_min: 0.0
    dropout_rate_max: 0.9

  predictor:
    layers_total_min: 5
    layers_total_max: 20
    units_per_layer_min: 32
    units_per_layer_max: 256

# Hyperparameters to optimize on validation data
# Focus on generalization and regularization
val:
  encoder:
    dropout_rate_min: 0.0
    dropout_rate_max: 0.9


# Hyperparameters to optimize on test data
# Focus on final performance and robustness
test:
  optimizer: adam
