hydra:
  run:
    dir: ./../outputs/${now:%Y-%m-%d-%H:%M}
  sweep:
    dir: ./../outputs
    subdir: ${now:%Y-%m-%d-%H:%M:%S}_${hydra:job.num}


defaults:
  - _self_
  - datamodule: vecset
  - model: trsfm_clssification
  - trainer: default